package cn.com.dhcc.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://test.dhcc.com.cn/")
public interface HelloWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "HelloWord")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "HelloWord", targetNamespace = "http://test.dhcc.com.cn/", className = "cn.com.dhcc.test.HelloWord")
	@ResponseWrapper(localName = "HelloWordResponse", targetNamespace = "http://test.dhcc.com.cn/", className = "cn.com.dhcc.test.HelloWordResponse")
	public String helloWord(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
