package cn.com.dhcc.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HelloWebServiceService service = new HelloWebServiceService();
 * HelloWebService portType = service.getHelloWebServicePort();
 * portType.helloWord(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HelloWebServiceService", targetNamespace = "http://test.dhcc.com.cn/", wsdlLocation = "http://10.1.132.70:8080/HttpService/HelloWebServicePort?wsdl")
public class HelloWebServiceService extends Service {

	private final static URL HELLOWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.dhcc.test.HelloWebServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.dhcc.test.HelloWebServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.1.132.70:8080/HttpService/HelloWebServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.1.132.70:8080/HttpService/HelloWebServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HELLOWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public HelloWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HelloWebServiceService() {
		super(HELLOWEBSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://test.dhcc.com.cn/", "HelloWebServiceService"));
	}

	/**
	 * 
	 * @return returns HelloWebService
	 */
	@WebEndpoint(name = "HelloWebServicePort")
	public HelloWebService getHelloWebServicePort() {
		return super.getPort(new QName("http://test.dhcc.com.cn/",
				"HelloWebServicePort"), HelloWebService.class);
	}

}
